const nodemailer = require('nodemailer');

const sendAlertEmail = async ({ lowStockItems, expiringItems, csvContent }) => {
  const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, ALERT_RECIPIENT } = process.env;
  
  if (!SMTP_HOST || !SMTP_PORT || !SMTP_USER || !SMTP_PASS || !ALERT_RECIPIENT) {
    console.warn('⚠️ Mail alerts skipped: SMTP credentials are not fully configured in .env file.');
    throw new Error('SMTP credentials are not fully configured in your .env file. Please check SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, and ALERT_RECIPIENT.');
  }

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT, 10),
    secure: parseInt(SMTP_PORT, 10) === 465,
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS
    }
  });

  let lowStockRows = '';
  if (lowStockItems && lowStockItems.length > 0) {
    lowStockItems.forEach(item => {
      lowStockRows += `
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold; color: #b91c1c;">${item.name}</td>
          <td style="padding: 8px; border-bottom: 1px solid #ddd;">${item.category}</td>
          <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold; text-align: right; color: #b91c1c;">${item.quantity}</td>
          <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">${item.reorderLevel}</td>
        </tr>
      `;
    });
  } else {
    lowStockRows = `<tr><td colspan="4" style="padding: 12px; text-align: center; color: #16a34a;">✅ All medicines are well-stocked!</td></tr>`;
  }

  let expiringRows = '';
  if (expiringItems && expiringItems.length > 0) {
    expiringItems.forEach(item => {
      const daysLeft = Math.ceil((new Date(item.expiryDate) - new Date()) / (1000 * 60 * 60 * 24));
      const color = daysLeft <= 30 ? '#b91c1c' : '#d97706';
      expiringRows += `
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold; color: ${color};">${item.name}</td>
          <td style="padding: 8px; border-bottom: 1px solid #ddd;">${item.batchNumber}</td>
          <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold; color: ${color};">${new Date(item.expiryDate).toLocaleDateString('en-IN')}</td>
          <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">${daysLeft} days</td>
        </tr>
      `;
    });
  } else {
    expiringRows = `<tr><td colspan="4" style="padding: 12px; text-align: center; color: #16a34a;">✅ No medicines expiring within 60 days!</td></tr>`;
  }

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 12px;">
      <h2 style="color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-top: 0;">🏥 MediCare Pharmacy System Alert</h2>
      
      <p style="font-size: 15px; color: #4b5563; line-height: 1.5;">
        This is an automated alert generated by your pharmacy management system. Please find the summary below and the attached detailed CSV report.
      </p>

      <h3 style="color: #b91c1c; margin-top: 25px; border-bottom: 1px solid #fee2e2; padding-bottom: 5px;">⚠️ Low Stock Items (${lowStockItems ? lowStockItems.length : 0})</h3>
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <thead>
          <tr style="background-color: #fef2f2; text-align: left;">
            <th style="padding: 8px; border-bottom: 2px solid #ddd;">Medicine</th>
            <th style="padding: 8px; border-bottom: 2px solid #ddd;">Category</th>
            <th style="padding: 8px; border-bottom: 2px solid #ddd; text-align: right;">Stock</th>
            <th style="padding: 8px; border-bottom: 2px solid #ddd; text-align: right;">Reorder Level</th>
          </tr>
        </thead>
        <tbody>
          ${lowStockRows}
        </tbody>
      </table>

      <h3 style="color: #d97706; margin-top: 30px; border-bottom: 1px solid #fef3c7; padding-bottom: 5px;">📅 Expiring Soon (${expiringItems ? expiringItems.length : 0})</h3>
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <thead>
          <tr style="background-color: #fffbeb; text-align: left;">
            <th style="padding: 8px; border-bottom: 2px solid #ddd;">Medicine</th>
            <th style="padding: 8px; border-bottom: 2px solid #ddd;">Batch No.</th>
            <th style="padding: 8px; border-bottom: 2px solid #ddd;">Expiry Date</th>
            <th style="padding: 8px; border-bottom: 2px solid #ddd; text-align: right;">Remaining</th>
          </tr>
        </thead>
        <tbody>
          ${expiringRows}
        </tbody>
      </table>

      <hr style="margin-top: 40px; border: 0; border-top: 1px solid #e5e7eb;" />
      <p style="font-size: 12px; color: #9ca3af; text-align: center;">
        Srinagar, Jammu & Kashmir | MediCare System v1.0
      </p>
    </div>
  `;

  const mailOptions = {
    from: `"MediCare Alert System" <${SMTP_USER}>`,
    to: ALERT_RECIPIENT,
    subject: `🚨 MediCare Alert: ${lowStockItems.length} Low Stock & ${expiringItems.length} Expiring Medicines`,
    html: htmlContent
  };

  if (csvContent) {
    mailOptions.attachments = [
      {
        filename: `medicare_inventory_alerts_${new Date().toISOString().slice(0, 10)}.csv`,
        content: csvContent
      }
    ];
  }

  const info = await transporter.sendMail(mailOptions);
  console.log(`✉️ Alert email successfully sent: ${info.messageId}`);
  return info;
};

module.exports = {
  sendAlertEmail
};
